/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ClawStudio AI Agent Orchestration Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all agent sessions
 */
export const listAgentsQueryLimitDefault = 50;

export const ListAgentsQueryParams = zod.object({
  status: zod.enum(["running", "idle", "failed", "completed"]).optional(),
  limit: zod.coerce.number().default(listAgentsQueryLimitDefault),
});

export const ListAgentsResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  model: zod.string(),
  status: zod.enum(["running", "idle", "failed", "completed"]),
  channel: zod.string().optional(),
  tokensUsed: zod.number(),
  tokensLimit: zod.number(),
  loopCount: zod.number(),
  lastActivity: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});
export const ListAgentsResponse = zod.array(ListAgentsResponseItem);

/**
 * @summary Create a new agent session
 */
export const CreateAgentBody = zod.object({
  name: zod.string(),
  model: zod.string(),
  channel: zod.string().optional(),
  tokensLimit: zod.number().optional(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary Get agent session by ID
 */
export const GetAgentParams = zod.object({
  id: zod.coerce.string(),
});

export const GetAgentResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  model: zod.string(),
  status: zod.enum(["running", "idle", "failed", "completed"]),
  channel: zod.string().optional(),
  tokensUsed: zod.number(),
  tokensLimit: zod.number(),
  loopCount: zod.number(),
  lastActivity: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary Update agent session status
 */
export const UpdateAgentParams = zod.object({
  id: zod.coerce.string(),
});

export const UpdateAgentBody = zod.object({
  status: zod.enum(["running", "idle", "failed", "completed"]).optional(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

export const UpdateAgentResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  model: zod.string(),
  status: zod.enum(["running", "idle", "failed", "completed"]),
  channel: zod.string().optional(),
  tokensUsed: zod.number(),
  tokensLimit: zod.number(),
  loopCount: zod.number(),
  lastActivity: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary Terminate and delete an agent session
 */
export const DeleteAgentParams = zod.object({
  id: zod.coerce.string(),
});

/**
 * Executes the agent against the Gemini API with all enabled skills wired in
as function declarations. The runner loops up to `maxSteps` times, executing
any tool calls the model emits, feeding results back, and returning the full
trace plus a final natural-language answer. All steps are persisted to memory_logs.

 * @summary Run an agent loop with Gemini and live function-calling
 */
export const RunAgentParams = zod.object({
  id: zod.coerce.string(),
});

export const runAgentBodyMaxStepsMax = 12;

export const RunAgentBody = zod.object({
  prompt: zod.string(),
  model: zod.string().optional(),
  maxSteps: zod.number().min(1).max(runAgentBodyMaxStepsMax).optional(),
  systemInstruction: zod.string().optional(),
});

export const RunAgentResponse = zod.object({
  agentId: zod.string(),
  prompt: zod.string(),
  finalAnswer: zod.string(),
  steps: zod.array(
    zod.object({
      step: zod.number(),
      type: zod.enum(["model", "tool_call", "tool_result", "final"]),
      toolName: zod.string().optional(),
      toolArgs: zod.record(zod.string(), zod.unknown()).optional(),
      toolResult: zod.unknown().optional(),
      text: zod.string().optional(),
      durationMs: zod.number(),
      promptTokens: zod.number().optional(),
      completionTokens: zod.number().optional(),
    }),
  ),
  totalTokens: zod.number(),
  loops: zod.number(),
  durationMs: zod.number(),
  status: zod.enum(["completed", "failed"]),
  error: zod.string().optional(),
});

/**
 * One-shot helper for testing — creates a temporary agent, runs the prompt, returns the result.
 * @summary Create an ephemeral agent and run it in a single call
 */
export const runAgentOnceBodyMaxStepsMax = 12;

export const RunAgentOnceBody = zod.object({
  prompt: zod.string(),
  name: zod.string().optional(),
  model: zod.string().optional(),
  maxSteps: zod.number().min(1).max(runAgentOnceBodyMaxStepsMax).optional(),
});

export const RunAgentOnceResponse = zod.object({
  agentId: zod.string(),
  prompt: zod.string(),
  finalAnswer: zod.string(),
  steps: zod.array(
    zod.object({
      step: zod.number(),
      type: zod.enum(["model", "tool_call", "tool_result", "final"]),
      toolName: zod.string().optional(),
      toolArgs: zod.record(zod.string(), zod.unknown()).optional(),
      toolResult: zod.unknown().optional(),
      text: zod.string().optional(),
      durationMs: zod.number(),
      promptTokens: zod.number().optional(),
      completionTokens: zod.number().optional(),
    }),
  ),
  totalTokens: zod.number(),
  loops: zod.number(),
  durationMs: zod.number(),
  status: zod.enum(["completed", "failed"]),
  error: zod.string().optional(),
});

/**
 * Phase 1 of the Fan-Out architecture. Accepts task_count and mock_duration_ms,
spawns that many concurrent async tasks via Promise.all, and returns once all
have settled. Each task records started_at and completed_at so callers can
verify true parallelism (spread of started_at across tasks should be ~zero).

 * @summary Spawn N concurrent mock tasks (true Promise.all parallelism)
 */
export const fanOutTasksBodyTaskCountMax = 100;

export const fanOutTasksBodyMockDurationMsMax = 30000;

export const FanOutTasksBody = zod.object({
  task_count: zod.number().min(1).max(fanOutTasksBodyTaskCountMax),
  mock_duration_ms: zod.number().min(1).max(fanOutTasksBodyMockDurationMsMax),
});

export const FanOutTasksResponse = zod.object({
  taskCount: zod.number(),
  mockDurationMs: zod.number(),
  startedAt: zod.coerce.date(),
  completedAt: zod.coerce.date(),
  totalDurationMs: zod.number(),
  startSpreadMs: zod.number(),
  speedupFactor: zod.number(),
  tasks: zod.array(
    zod.object({
      taskId: zod.string(),
      index: zod.number(),
      status: zod.enum(["completed", "failed"]),
      startedAt: zod.coerce.date(),
      completedAt: zod.coerce.date(),
      durationMs: zod.number(),
      result: zod.string().optional(),
    }),
  ),
});

/**
 * @summary Get aggregated agent status counts and token usage
 */
export const GetAgentSummaryResponse = zod.object({
  total: zod.number(),
  running: zod.number(),
  idle: zod.number(),
  failed: zod.number(),
  completed: zod.number(),
  totalTokensUsed: zod.number(),
  avgLoopCount: zod.number(),
  activeChannels: zod.number(),
});

/**
 * @summary List all MCP skills and tools
 */
export const ListSkillsQueryParams = zod.object({
  enabled: zod.coerce.boolean().optional(),
  category: zod.coerce.string().optional(),
});

export const ListSkillsResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  enabled: zod.boolean(),
  executionPolicy: zod.enum(["auto", "manual", "restricted", "disabled"]),
  callCount: zod.number(),
  lastCalled: zod.coerce.date().optional(),
  avgLatencyMs: zod.number().optional(),
  tags: zod.array(zod.string()).optional(),
  createdAt: zod.coerce.date(),
});
export const ListSkillsResponse = zod.array(ListSkillsResponseItem);

/**
 * @summary Register a new skill/tool
 */
export const CreateSkillBody = zod.object({
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  executionPolicy: zod
    .enum(["auto", "manual", "restricted", "disabled"])
    .optional(),
  tags: zod.array(zod.string()).optional(),
});

/**
 * @summary Enable/disable a skill or update its execution policy
 */
export const UpdateSkillParams = zod.object({
  id: zod.coerce.string(),
});

export const UpdateSkillBody = zod.object({
  enabled: zod.boolean().optional(),
  executionPolicy: zod
    .enum(["auto", "manual", "restricted", "disabled"])
    .optional(),
  description: zod.string().optional(),
});

export const UpdateSkillResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  description: zod.string(),
  category: zod.string(),
  enabled: zod.boolean(),
  executionPolicy: zod.enum(["auto", "manual", "restricted", "disabled"]),
  callCount: zod.number(),
  lastCalled: zod.coerce.date().optional(),
  avgLatencyMs: zod.number().optional(),
  tags: zod.array(zod.string()).optional(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List memory and trace logs
 */
export const listLogsQueryLimitDefault = 100;

export const ListLogsQueryParams = zod.object({
  agentId: zod.coerce.string().optional(),
  type: zod.enum(["memory", "trace", "tool_call", "webhook"]).optional(),
  limit: zod.coerce.number().default(listLogsQueryLimitDefault),
});

export const ListLogsResponseItem = zod.object({
  id: zod.string(),
  agentId: zod.string(),
  type: zod.enum(["memory", "trace", "tool_call", "webhook"]),
  level: zod.enum(["info", "warn", "error", "debug"]),
  message: zod.string(),
  payload: zod.record(zod.string(), zod.unknown()).optional(),
  toolName: zod.string().optional(),
  durationMs: zod.number().optional(),
  timestamp: zod.coerce.date(),
});
export const ListLogsResponse = zod.array(ListLogsResponseItem);

/**
 * @summary Get full DAG trace for a specific agent session
 */
export const GetAgentTraceParams = zod.object({
  agentId: zod.coerce.string(),
});

export const GetAgentTraceResponse = zod.object({
  agentId: zod.string(),
  sessionName: zod.string(),
  messages: zod.array(
    zod.object({
      id: zod.string(),
      role: zod.enum(["user", "assistant", "system", "tool"]),
      content: zod.string(),
      toolCall: zod.record(zod.string(), zod.unknown()).optional(),
      timestamp: zod.coerce.date(),
    }),
  ),
  dagSteps: zod.array(
    zod.object({
      stepId: zod.string(),
      type: zod.enum([
        "llm_call",
        "tool_call",
        "memory_read",
        "memory_write",
        "webhook_out",
      ]),
      toolName: zod.string().optional(),
      input: zod.record(zod.string(), zod.unknown()).optional(),
      output: zod.record(zod.string(), zod.unknown()).optional(),
      status: zod.enum(["pending", "running", "success", "error"]),
      durationMs: zod.number().optional(),
      timestamp: zod.coerce.date(),
    }),
  ),
  totalTokens: zod.number(),
  durationMs: zod.number(),
});

/**
 * @summary Ingest a webhook event from a channel (Slack, WhatsApp, etc.)
 */
export const IngestWebhookParams = zod.object({
  channel: zod.enum(["slack", "whatsapp", "email", "generic"]),
});

export const IngestWebhookBody = zod.object({
  externalId: zod.string().optional(),
  from: zod.string(),
  body: zod.string(),
  attachments: zod.array(zod.string()).optional(),
  metadata: zod.record(zod.string(), zod.unknown()).optional(),
});

/**
 * @summary List configured webhook channels
 */
export const ListChannelConfigsResponseItem = zod.object({
  id: zod.string(),
  channel: zod.enum(["slack", "whatsapp", "email", "generic"]),
  enabled: zod.boolean(),
  webhookUrl: zod.string().optional(),
  eventsReceived: zod.number(),
  lastEvent: zod.coerce.date().optional(),
  createdAt: zod.coerce.date(),
});
export const ListChannelConfigsResponse = zod.array(
  ListChannelConfigsResponseItem,
);

/**
 * @summary Get token usage over time (for charts)
 */
export const getTokenMetricsQueryPeriodDefault = `24h`;

export const GetTokenMetricsQueryParams = zod.object({
  period: zod
    .enum(["1h", "6h", "24h", "7d"])
    .default(getTokenMetricsQueryPeriodDefault),
});

export const GetTokenMetricsResponse = zod.object({
  period: zod.string(),
  dataPoints: zod.array(
    zod.object({
      timestamp: zod.string(),
      promptTokens: zod.number(),
      completionTokens: zod.number(),
      totalTokens: zod.number(),
    }),
  ),
  totalTokens: zod.number(),
  promptTokens: zod.number(),
  completionTokens: zod.number(),
  estimatedCostUsd: zod.number(),
});
